### ISSUE TITLE
Exception when getting posts

### ISSUE THREAD

**Issue by rlrs** [Foxite/PatreonDownloader#1]
I get this exception when trying to get posts. Maybe something has changed?

> System.Collections.Generic.KeyNotFoundException: The given key 'post_tag' was not present in the dictionary.
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at PatreonDownloader.CustomStringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\Users\Foxite\source\repos\PatreonDownloader\PatreonDownloader\CustomStringEnumConverter.cs:line 26
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at PatreonDownloader.Program.DownloadAllPosts(HttpClient client, List`1 pages, String backupFile) in C:\Users\Foxite\source\repos\PatreonDownloader\PatreonDownloader\Program.cs:line 202
>    at PatreonDownloader.Program.Main(String[] args) in C:\Users\Foxite\source\repos\PatreonDownloader\PatreonDownloader\Program.cs:line 93

**Comment by Foxite** [comment]
Something has certainly changed, Youtube often changes their site's internal layout quite drastically to stop apps like this from working. I'll see if there's been an update to the scraping library and push an update shortly.

**Comment by Foxite** [comment]
I posted a reply but didn't realize that this is not, in fact, my other project which deals in youtube downloading. Hang tight, I'll take a look

**Comment by Foxite** [comment]
I've released an update which should fix this problem.

**Comment by rlrs** [comment]
That was fast, nice. It does get all the posts now. 
It doesn't download anything afterwards (yes, I ran it again), but I guess it's only for image posts and not e.g. youtube links. Anyways thanks, I can parse the json to get what I need.

**Comment by Foxite** [comment]
It can fish links out of posts and download extra media from those links, but right now I've only done that for Dropbox links. It could download youtube videos as well.
